# Generated by Django 4.0.1 on 2022-09-23 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hash_key', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('basemodel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='child_datasource', serialize=False, to='projects.basemodel')),
                ('document', models.TextField()),
                ('json', models.JSONField(blank=True, null=True)),
                ('last_cached', models.DateTimeField(blank=True, null=True)),
                ('selected_viz', models.IntegerField(blank=True, null=True)),
                ('learner_mode', models.BooleanField(default=False)),
            ],
            options={
                'default_related_name': 'datasources',
            },
            bases=('projects.basemodel',),
        ),
        migrations.CreateModel(
            name='Viz',
            fields=[
                ('basemodel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='child_viz', serialize=False, to='projects.basemodel')),
                ('json', models.JSONField(blank=True, null=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.datasource')),
            ],
            options={
                'default_related_name': 'vizs',
            },
            bases=('projects.basemodel',),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('basemodel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='child_report', serialize=False, to='projects.basemodel')),
                ('report', models.TextField()),
                ('share', models.BooleanField(default=False)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.datasource')),
            ],
            options={
                'default_related_name': 'reports',
            },
            bases=('projects.basemodel',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('basemodel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='child_project', serialize=False, to='projects.basemodel')),
                ('selected_datasource', models.IntegerField(blank=True, null=True)),
                ('learner_mode', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('projects.basemodel',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('basemodel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='child_item', serialize=False, to='projects.basemodel')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.datasource')),
            ],
            options={
                'default_related_name': 'items',
            },
            bases=('projects.basemodel',),
        ),
        migrations.AddField(
            model_name='datasource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('basemodel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='child_answer', serialize=False, to='projects.basemodel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.item')),
                ('viz', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.viz')),
            ],
            options={
                'default_related_name': 'answers',
            },
            bases=('projects.basemodel',),
        ),
    ]
