# Generated by Django 4.1.4 on 2023-11-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="description",
            field=models.CharField(blank=True, default="New item", max_length=255),
        ),
        migrations.AlterField(
            model_name="answer",
            name="name",
            field=models.CharField(blank=True, default="New item", max_length=100),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="description",
            field=models.CharField(blank=True, default="New item", max_length=255),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="name",
            field=models.CharField(blank=True, default="New item", max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.CharField(blank=True, default="New item", max_length=255),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(blank=True, default="New item", max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(blank=True, default="New item", max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(blank=True, default="New item", max_length=100),
        ),
        migrations.AlterField(
            model_name="report",
            name="description",
            field=models.CharField(blank=True, default="New item", max_length=255),
        ),
        migrations.AlterField(
            model_name="report",
            name="name",
            field=models.CharField(blank=True, default="New item", max_length=100),
        ),
        migrations.AlterField(
            model_name="viz",
            name="description",
            field=models.CharField(blank=True, default="New item", max_length=255),
        ),
        migrations.AlterField(
            model_name="viz",
            name="name",
            field=models.CharField(blank=True, default="New item", max_length=100),
        ),
    ]
