# Generated by Django 4.1.4 on 2024-01-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "title",
                    models.CharField(
                        blank=True, default="New notification title", max_length=100
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, default="New notification message", max_length=200
                    ),
                ),
                ("html", models.CharField(blank=True, max_length=1000)),
                ("dismissable", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("LIST", "List"), ("VIEW", "View")],
                        default="LIST",
                        max_length=4,
                    ),
                ),
            ],
        ),
    ]
