# Generated by Django 4.0.1 on 2022-07-25 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'default_related_name': 'answers'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'default_related_name': 'files'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'default_related_name': 'items'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'default_related_name': 'reports'},
        ),
        migrations.AlterModelOptions(
            name='viz',
            options={'default_related_name': 'vizs'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.item'),
        ),
        migrations.AlterField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.file'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.file'),
        ),
        migrations.AlterField(
            model_name='viz',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.file'),
        ),
    ]
