# Generated by Django 4.0.1 on 2022-09-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'default_related_name': 'reports'},
        ),
    ]
