# Generated by Django 4.0.1 on 2022-07-26 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.file'),
        ),
    ]
