# Generated by Django 4.1.4 on 2024-04-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="datastream",
            name="last_cached",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
