# Generated by Django 4.0.1 on 2022-08-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
