# Generated by Django 4.1.4 on 2024-04-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_settings_alter_datastream_last_cached"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="user",
            new_name="owner",
        ),
    ]
