# Generated by Django 4.1.4 on 2024-01-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="position",
            field=models.CharField(
                choices=[("LIST", "List"), ("VIEW", "View")],
                default="LIST",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[("INF", "Info"), ("DAN", "Danger")],
                default="INF",
                max_length=3,
            ),
        ),
    ]
