# Generated by Django 4.1.4 on 2024-05-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_activity_is_published_comment_is_published_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datasource",
            options={
                "default_related_name": "datasources",
                "permissions": [
                    ("can_view_published_datasource", "Can view published datasource")
                ],
            },
        ),
    ]
