# Generated by Django 4.0.1 on 2022-07-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_file_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='selected_viz',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
