# Generated by Django 4.1.4 on 2024-10-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_comment_collaborators_remove_comment_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datastream",
            options={
                "default_related_name": "datastreams",
                "permissions": [
                    ("view_published_datastream", "Can view published datastream")
                ],
            },
        ),
        migrations.AlterField(
            model_name="activity",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cover",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="datapod",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="datastream",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="viz",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
