# Generated by Django 4.1.4 on 2024-10-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0003_alter_datastream_options_alter_activity_is_published_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="itemview",
            name="session",
            field=models.CharField(default="NA", max_length=40),
            preserve_default=False,
        ),
    ]
