# Generated by Django 4.1.4 on 2023-12-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Datastream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="New item", max_length=100),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="New item", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("hash_key", models.CharField(blank=True, max_length=10)),
                ("url", models.URLField()),
            ],
            options={
                "default_related_name": "datastreams",
            },
        ),
        migrations.DeleteModel(
            name="Source",
        ),
    ]
