# Generated by Django 4.0.1 on 2022-07-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_file_selected_viz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.TextField(),
        ),
    ]
