# Generated by Django 4.1.4 on 2023-12-22 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0003_profile_created_at_profile_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="slug",
            field=models.SlugField(default="zz", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datastream",
            name="slug",
            field=models.SlugField(default="zz", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(default="zz", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="viz",
            name="slug",
            field=models.SlugField(default="zz", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
