# Generated by Django 4.1.4 on 2024-05-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_datasource_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datasource",
            options={
                "default_related_name": "datasources",
                "permissions": [
                    ("view_published_datasource", "Can view published datasource")
                ],
            },
        ),
    ]
