# Generated by Django 4.1.4 on 2024-01-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_notification_position_alter_notification_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="instructions",
            field=models.CharField(
                blank=True, default="New notification instructions", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[("INF", "Info"), ("DAN", "Danger"), ("NON", "None")],
                default="INF",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="position",
            field=models.CharField(
                choices=[
                    ("LIST", "List"),
                    ("LAD", "List Ad"),
                    ("VIEW", "View"),
                    ("VAD", "View ad"),
                    ("USER", "User"),
                    ("UAD", "User ad"),
                ],
                default="LIST",
                max_length=4,
            ),
        ),
    ]
