# Generated by Django 4.0.1 on 2022-07-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_file_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField()),
                ('file', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.file')),
            ],
        ),
    ]
