# Generated by Django 4.1.4 on 2024-10-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_itemview_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemview",
            name="session",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
