# Generated by Django 4.1.4 on 2023-12-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_datasource_slug_datastream_slug_profile_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IPAddress", models.GenericIPAddressField(default="45.243.82.169")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.datasource",
                    ),
                ),
            ],
        ),
    ]
