# Generated by Django 4.1.4 on 2023-12-02 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_datastream_delete_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="datastream",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.datastream",
            ),
            preserve_default=False,
        ),
    ]
