# Generated by Django 4.1.4 on 2023-12-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_itemviews"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ItemViews",
            new_name="ItemView",
        ),
    ]
