# Generated by Django 4.1.4 on 2024-10-06 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_itemview_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
