# Generated by Django 4.1.4 on 2023-12-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_datasource_datastream"),
    ]

    operations = [
        migrations.AddField(
            model_name="datastream",
            name="json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
