# Generated by Django 4.0.1 on 2022-07-18 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.file')),
            ],
            bases=('projects.file',),
        ),
        migrations.AddField(
            model_name='project',
            name='learner_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.mission')),
                ('viz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.viz')),
            ],
        ),
    ]
