# Generated by Django 4.1.4 on 2023-12-02 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_datastream_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
    ]
