# Generated by Django 4.1.4 on 2024-11-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_itemview_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="datastream",
            name="datastream_type",
            field=models.CharField(
                choices=[("C", "CSV"), ("E", "Excel"), ("K", "CKAN")],
                default="C",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
