# Generated by Django 4.0.1 on 2022-07-18 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_mission_project_learner_mode_step'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Step',
            new_name='Item',
        ),
        migrations.AddField(
            model_name='file',
            name='learner_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.file'),
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
    ]
