# Generated by Django 4.1.4 on 2024-11-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_datastream_datastream_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datastream",
            name="datastream_type",
            field=models.CharField(
                choices=[("C", "CSV"), ("E", "Excel"), ("K", "CKAN")],
                default="C",
                max_length=1,
            ),
        ),
    ]
