# Generated by Django 4.1.4 on 2023-12-03 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_datasource_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="datastream",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.datastream",
            ),
        ),
    ]
