# Generated by Django 4.0.1 on 2022-07-23 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_step_item_file_learner_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='viz',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.item')),
                ('viz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.viz')),
            ],
        ),
    ]
