# Generated by Django 4.1.4 on 2023-12-26 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_remove_itemview_item_itemview_datasource_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"default_related_name": "activities"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"default_related_name": "comments"},
        ),
        migrations.AlterModelOptions(
            name="itemview",
            options={"default_related_name": "itemviews"},
        ),
        migrations.AddField(
            model_name="comment",
            name="datasource",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.datasource",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.profile",
            ),
        ),
    ]
