"""
Django settings for dj_test project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent

# Using heroku provided code
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
#STATICFILES_DIRS = (
#    os.path.join(BASE_DIR, 'static'),
#)

DATA_UPLOAD_MAX_MEMORY_SIZE = 10242880

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

MEDIA_ROOT= os.path.join(BASE_DIR, 'media/')
MEDIA_URL= "/media/"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-kfz#ag8=&yb1lynyfj0v=k%et%5++u08(q%@q(839gwqd-reah'

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 
                            'django-insecure-kfz#ag8=&yb1lynyfj0v=k%et%5++u08(q%@q(839gwqd-reah')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
#DEBUG = False
DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'

#HTML_MINIFY = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    #'django.contrib.staticfiles',
    'projects.apps.ProjectsStaticFilesConfig',
    'projects.apps.ProjectsConfig',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'pwa',
    'auditlog',
    'analytical',
    'django_unicorn',
    'guardian',
    #'projects',
]

#SOCIALACCOUNT_AUTO_SIGNUP = False

MIDDLEWARE = [
    # Request altering middleware
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'projects.middleware.guardian_anonymous_user_middleware',
    'projects.middleware.RedirectMiddleware',
    'projects.middleware.GarbageCollectionMiddleware',
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        "LOCATION": os.environ.get('REDIS_URL', ''),
        "OPTIONS": {
                "ssl_cert_reqs": None
        },
    }
}

if DEBUG:
    #http://localhost:8000
    SITE_ID = 3
    SITE_DOMAIN_NAME = 'localhost:8000'
    INSTALLED_APPS += ['debug_toolbar','pympler',]
    MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware',]
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            "TIMEOUT": 300,
        }
    }
else:
    #https://prod
    SITE_ID = 2
    SITE_DOMAIN_NAME = 'youviz.app'
    #ALLOWED_HOSTS = ["youviz.app"]
    CSRF_TRUSTED_ORIGINS = ["https://www.youviz.app", "https://youviz.app"]
    #CSRF_ALLOWED_ORIGINS = ["https://youviz.app"]
    #CORS_ORIGINS_WHITELIST = ["https://youviz.app"]
    #SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    import sentry_sdk
    sentry_sdk.init(
        dsn="https://959b0b0d53d2705c6a09b29b945588b6@o4508148174225408.ingest.us.sentry.io/4508148182548480",
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for tracing.
        traces_sample_rate=1.0,
        # Set profiles_sample_rate to 1.0 to profile 100%
        # of sampled transactions.
        # We recommend adjusting this value in production.
        profiles_sample_rate=1.0,
    )


SITE_DISPLAY_NAME = SITE_DOMAIN_NAME

'''

def get_cache():
    try:
        servers = os.environ['MEMCACHIER_SERVERS']
        username = os.environ['MEMCACHIER_USERNAME']
        password = os.environ['MEMCACHIER_PASSWORD']
        return {
          'default': {
            'BACKEND': 'django_bmemcached.memcached.BMemcached',
            # TIMEOUT is not the connection timeout! It's the default expiration
            # timeout that should be applied to keys! Setting it to `None`
            # disables expiration.
            'TIMEOUT': None,
            'LOCATION': servers,
            'OPTIONS': {
              'username': username,
              'password': password,
            }
          }
        }
    except:
        return {
          'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'
          }
        }

CACHES = get_cache()
'''
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": ["project/templates/"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]


AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

ANONYMOUS_USER_NAME = 'GuardianUser'

#GUARDIAN_AUTO_PREFETCH = True

LOGIN_REDIRECT_URL = '/'

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
    "127.0.0.1",
]

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda r: DEBUG, # show if DEBUG mode
}

DEBUG_TOOLBAR_PANELS = (
    'pympler.panels.MemoryPanel',
    'debug_toolbar.panels.history.HistoryPanel',
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
)

#import gc
#gc.set_debug(gc.DEBUG_LEAK)

# settings.py
UNICORN = {
    "SCRIPT_LOCATION": "after",
#    "SCRIPT_LOCATION": "append",
}

# Configure Django App for Heroku.
import django_heroku
django_heroku.settings(locals())

# pwa
PWA_APP_NAME = 'YouViz'
PWA_APP_DESCRIPTION = "Search, Vizualize and Share Open Data"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        #'src': '/static/images/icons/icon-144x144.png',
        'src': '/static/projects/img/icons/yvlogo.png',
        'sizes': '144x144'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        #'src': '/static/images/icons/icon-144x144.png',
        'src': '/static/projects/img/icons/yvlogo.png',
        'sizes': '144x144'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/projects/img/icons/iPhone_14_Pro_Max_landscape.png',
        'media': '(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_14_Pro_landscape.png',
        'media': '(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_landscape.png',
        'media': '(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_landscape.png',
        'media': '(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_landscape.png',
        'media': '(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_11_Pro_Max__iPhone_XS_Max_landscape.png',
        'media': '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_11__iPhone_XR_landscape.png',
        'media': '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_landscape.png',
        'media': '(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_landscape.png',
        'media': '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/4__iPhone_SE__iPod_touch_5th_generation_and_later_landscape.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/12.9__iPad_Pro_landscape.png',
        'media': '(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/11__iPad_Pro__10.5__iPad_Pro_landscape.png',
        'media': '(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/10.9__iPad_Air_landscape.png',
        'media': '(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/10.5__iPad_Air_landscape.png',
        'media': '(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/10.2__iPad_landscape.png',
        'media': '(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/9.7__iPad_Pro__7.9__iPad_mini__9.7__iPad_Air__9.7__iPad_landscape.png',
        'media': '(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/8.3__iPad_Mini_landscape.png',
        'media': '(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_14_Pro_Max_portrait.png',
        'media': '(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_14_Pro_portrait.png',
        'media': '(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_portrait.png',
        'media': '(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_portrait.png',
        'media': '(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_portrait.png',
        'media': '(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_11_Pro_Max__iPhone_XS_Max_portrait.png',
        'media': '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_11__iPhone_XR_portrait.png',
        'media': '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_portrait.png',
        'media': '(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_portrait.png',
        'media': '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/4__iPhone_SE__iPod_touch_5th_generation_and_later_portrait.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/12.9__iPad_Pro_portrait.png',
        'media': '(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/11__iPad_Pro__10.5__iPad_Pro_portrait.png',
        'media': '(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/10.9__iPad_Air_portrait.png',
        'media': '(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/10.5__iPad_Air_portrait.png',
        'media': '(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/10.2__iPad_portrait.png',
        'media': '(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/9.7__iPad_Pro__7.9__iPad_mini__9.7__iPad_Air__9.7__iPad_portrait.png',
        'media': '(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    },
    {
        'src': '/static/projects/img/icons/8.3__iPad_Mini_portrait.png',
        'media': '(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    }
    
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'projects', 'templates', 'projects', 'serviceworker.js')

GOOGLE_ANALYTICS_GTAG_PROPERTY_ID = 'G-LDHFFBL5TS'

UNICORN = {
    #"APPS": ["unicorn",],
    #"CACHE_ALIAS": "default",
    #"MINIFY_HTML": False,
    "MINIFIED": True,
    "SERIAL": {
        "ENABLED": True,
        "TIMEOUT": 60,
    },
    #"SCRIPT_LOCATION": "after",
    #"MORPHER": {
    #    "NAME": "morphdom",
    #    "RELOAD_SCRIPT_ELEMENTS": False,
    #},
}


